CREATE TABLE RipDB.JokeTags (
	TagID INT NOT NULL,
	JokeID INT NOT NULL,
	IsPrimary BIT DEFAULT 0,
	CONSTRAINT PK_RipJokes PRIMARY KEY (TagID,JokeID),
	CONSTRAINT JokeTags_Tag_FK FOREIGN KEY (TagID) REFERENCES RipDB.Tags(TagID),
	CONSTRAINT JokeTags_Joke_FK FOREIGN KEY (JokeID) REFERENCES RipDB.Jokes(JokeID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Stores tags for jokes.';
