CREATE TABLE RipComposers (
	RipID INT NOT NULL,
	ComposerID INT NOT NULL,
	CONSTRAINT RipComposers_Composer_FK FOREIGN KEY (RipID) REFERENCES Rips(RipID),
	CONSTRAINT RipComposers_Rip_FK FOREIGN KEY (ComposerID) REFERENCES Composers(ComposerID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
AUTO_INCREMENT=1;
