CREATE TABLE RipGenres (
	RipID INT auto_increment NOT NULL,
	GenreID int NOT NULL,
	CONSTRAINT PK_RipGenres PRIMARY KEY (RipID, GenreID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
AUTO_INCREMENT=1;
