-- RipDB.RipJokes definition

CREATE TABLE RipDB.RipJokes (
	RipJokeId BIGINT NOT NULL AUTO_INCREMENT,
	RipId INT NOT NULL,
	JokeId INT NOT NULL,
	JokeTimestamp TIMESTAMP DEFAULT NULL,
	JokeComment varchar(1024) DEFAULT NULL,
	CONSTRAINT PK_RipJokes PRIMARY KEY (RipJokeId),
	CONSTRAINT RipJokes_Rips_FK FOREIGN KEY (RipId) REFERENCES RipDB.Rips(RipID),
	CONSTRAINT RipJokes_Jokes_FK FOREIGN KEY (JokeId) REFERENCES RipDB.Jokes(JokeID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
