CREATE TABLE RipRippers (
	RipID int NOT NULL,
	RipperId int NOT NULL,
	Alias varchar(256) CHARACTER SET utf8mb4 DEFAULT NULL,
	CONSTRAINT PK_RipRipper PRIMARY KEY (RipID,RipperID),
	CONSTRAINT RipID_FK FOREIGN KEY (RipID) REFERENCES Rips(RipID) ON DELETE CASCADE,
	CONSTRAINT RipperId_FK FOREIGN KEY (RipperId) REFERENCES Rippers(RipperId) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Stores associations between rips and rippers.'
AUTO_INCREMENT=1;
