CREATE TABLE Tags (
	TagID INT auto_increment NOT NULL,
	TagName nvarchar(128) NOT NULL,
	CONSTRAINT PK_Tags PRIMARY KEY (TagID),
	CONSTRAINT UQ_TagName UNIQUE KEY (TagName)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
AUTO_INCREMENT=1;
